// Copyright (c) clast-project. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

using Apache.Arrow;
using EngineeredWood.Expressions;
using EngineeredWood.Expressions.Arrow;
using EngineeredWood.Expressions.Arrow.Spark;
using EngineeredWood.Expressions.Sql;

namespace EngineeredWood.DeltaLake.Table;

/// <summary>
/// Materialises and validates the columns a table declares with
/// <c>delta.generationExpression</c>.
/// </summary>
/// <remarks>
/// <para>
/// Unlike a CHECK constraint, which only inspects a batch, this rewrites one: a generated column
/// the caller omitted is computed and added, and one the caller supplied is checked against what
/// the expression produces.
/// </para>
/// <para>
/// The check is the protocol's, verbatim — writers "MUST enforce that any data writing to the
/// table satisfy the condition <c>(&lt;value&gt; &lt;=&gt; &lt;generation expression&gt;) IS
/// TRUE</c>", where <c>&lt;=&gt;</c> is null-safe equality. Null-safe matters: a row that leaves
/// both the supplied value and the computed one null is conformant, and ordinary equality would
/// have called that null and refused it.
/// </para>
/// </remarks>
internal sealed class DeltaGeneratedColumns
{
    private readonly record struct Generated(string Name, string Sql, Expression Expression, Field Field);

    private readonly IReadOnlyList<Generated> _columns;
    private readonly ArrowRowEvaluator _evaluator;

    private DeltaGeneratedColumns(IReadOnlyList<Generated> columns)
    {
        _columns = columns;
        _evaluator = new ArrowRowEvaluator(new SparkFunctionRegistry());
    }

    /// <summary>Whether the table declares any generated column.</summary>
    /// <remarks>Does not parse — see <see cref="DeltaConstraintEnforcer.Declares"/> for why.</remarks>
    public static bool Declares(Snapshot.Snapshot snapshot)
    {
        foreach (var field in snapshot.ArrowSchema.FieldsList)
        {
            if (field.Metadata is not null && field.Metadata.ContainsKey("delta.generationExpression"))
                return true;
        }

        return false;
    }

    /// <summary>Builds a materialiser, or null when the table declares no generated column.</summary>
    /// <exception cref="DeltaFormatException">
    /// A generation expression is declared that this writer cannot parse; the write is refused
    /// rather than committed with a column nobody computed.
    /// </exception>
    public static DeltaGeneratedColumns? Create(Snapshot.Snapshot snapshot)
    {
        var columns = new List<Generated>();

        foreach (var field in snapshot.ArrowSchema.FieldsList)
        {
            if (field.Metadata is null
                || !field.Metadata.TryGetValue("delta.generationExpression", out var sql))
            {
                continue;
            }

            try
            {
                columns.Add(new Generated(field.Name, sql, SparkSqlParser.ParseExpression(sql), field));
            }
            catch (SparkSqlParseException ex)
            {
                throw new DeltaFormatException(
                    DeltaTableErrorCodes.UnevaluableTableExpression,
                    $"Column '{field.Name}' is generated by an expression this writer cannot parse, "
                    + $"so the write was refused rather than committed with a value nobody computed: "
                    + $"{ex.Reason} at position {ex.Position} in: {sql}",
                    ex);
            }
        }

        return columns.Count == 0 ? null : new DeltaGeneratedColumns(columns);
    }

    /// <summary>
    /// Returns <paramref name="batch"/> with every generated column present and correct.
    /// </summary>
    /// <exception cref="DeltaFormatException">
    /// A supplied value disagrees with the expression, or the expression cannot be evaluated.
    /// </exception>
    public RecordBatch Apply(RecordBatch batch)
    {
        var result = batch;

        foreach (var column in _columns)
        {
            var supplied = IndexOf(result, column.Name);

            if (supplied >= 0)
                ValidateSupplied(column, result);
            else
                result = Append(column, result);
        }

        return result;
    }

    /// <summary>Checks a caller-supplied value against the expression.</summary>
    private void ValidateSupplied(Generated column, RecordBatch batch)
    {
        // Built as the protocol states it rather than as an equality plus a null check, because
        // NullSafeEqual already produces true or false and never null — which is exactly what
        // "IS TRUE" is there to guarantee.
        var agrees = new ComparisonPredicate(
            new UnboundReference(column.Name), ComparisonOperator.NullSafeEqual, column.Expression);

        BooleanArray result;
        try
        {
            result = _evaluator.EvaluatePredicate(agrees, batch);
        }
        catch (Exception ex) when (ex is not DeltaFormatException)
        {
            throw Unevaluable(column, ex);
        }

        for (var row = 0; row < batch.Length; row++)
        {
            if (result.GetValue(row) is true)
                continue;

            throw new DeltaFormatException(
                DeltaTableErrorCodes.GeneratedColumnMismatch,
                $"Column '{column.Name}' is GENERATED ALWAYS AS ({column.Sql}), and a row being "
                + "written supplies a value the expression does not produce. Either omit the "
                + "column and let it be computed, or supply the value the expression gives. "
                + "No data was committed.");
        }
    }

    /// <summary>Computes the column and adds it to the batch.</summary>
    private RecordBatch Append(Generated column, RecordBatch batch)
    {
        IArrowArray values;
        try
        {
            // Materialised against the column's declared Arrow type rather than whatever the
            // expression happens to produce, so `CAST(ts AS DATE)` lands as the table's DATE
            // column instead of something merely date-shaped.
            values = _evaluator.EvaluateExpression(column.Expression, batch, column.Field.DataType);
        }
        catch (Exception ex) when (ex is not DeltaFormatException)
        {
            throw Unevaluable(column, ex);
        }

        var schema = new Apache.Arrow.Schema.Builder();
        var arrays = new List<IArrowArray>(batch.ColumnCount + 1);

        for (var i = 0; i < batch.ColumnCount; i++)
        {
            schema.Field(batch.Schema.FieldsList[i]);
            arrays.Add(batch.Column(i));
        }

        schema.Field(column.Field);
        arrays.Add(values);

        return new RecordBatch(schema.Build(), arrays, batch.Length);
    }

    private static DeltaFormatException Unevaluable(Generated column, Exception cause) =>
        new(
            DeltaTableErrorCodes.UnevaluableTableExpression,
            $"Column '{column.Name}' is generated by ({column.Sql}), which could not be evaluated "
            + $"against the data being written, so the write was refused: {cause.Message}",
            cause);

    private static int IndexOf(RecordBatch batch, string name)
    {
        for (var i = 0; i < batch.ColumnCount; i++)
        {
            if (string.Equals(batch.Schema.FieldsList[i].Name, name, StringComparison.Ordinal))
                return i;
        }

        return -1;
    }
}
