// Copyright (c) clast-project. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

using Apache.Arrow;
using EngineeredWood.Expressions;
using EngineeredWood.Expressions.Arrow;
using EngineeredWood.Expressions.Arrow.Spark;
using EngineeredWood.Expressions.Sql;

namespace EngineeredWood.DeltaLake.Table;

/// <summary>
/// Materialises and validates the columns a table declares with
/// <c>delta.generationExpression</c>.
/// </summary>
/// <remarks>
/// <para>
/// Unlike a CHECK constraint, which only inspects a batch, this rewrites one: a generated column
/// the caller omitted is computed and added, and one the caller supplied is checked against what
/// the expression produces.
/// </para>
/// <para>
/// The check is the protocol's, verbatim — writers "MUST enforce that any data writing to the
/// table satisfy the condition <c>(&lt;value&gt; &lt;=&gt; &lt;generation expression&gt;) IS
/// TRUE</c>", where <c>&lt;=&gt;</c> is null-safe equality. Null-safe matters: a row that leaves
/// both the supplied value and the computed one null is conformant, and ordinary equality would
/// have called that null and refused it.
/// </para>
/// </remarks>
internal sealed class DeltaGeneratedColumns
{
    private readonly record struct Generated(string Name, string Sql, Expression Expression, Field Field);

    private readonly IReadOnlyList<Generated> _columns;
    private readonly ArrowRowEvaluator _evaluator;

    private DeltaGeneratedColumns(IReadOnlyList<Generated> columns)
    {
        _columns = columns;
        _evaluator = new ArrowRowEvaluator(new SparkFunctionRegistry());
    }

    /// <summary>Whether the table declares any generated column.</summary>
    /// <remarks>Does not parse — see <see cref="DeltaConstraintEnforcer.Declares"/> for why.</remarks>
    public static bool Declares(Snapshot.Snapshot snapshot)
    {
        foreach (var field in snapshot.ArrowSchema.FieldsList)
        {
            if (field.Metadata is not null && field.Metadata.ContainsKey("delta.generationExpression"))
                return true;
        }

        return false;
    }

    /// <summary>Builds a materialiser, or null when the table declares no generated column.</summary>
    /// <exception cref="DeltaFormatException">
    /// A generation expression is declared that this writer cannot parse; the write is refused
    /// rather than committed with a column nobody computed.
    /// </exception>
    public static DeltaGeneratedColumns? Create(Snapshot.Snapshot snapshot)
    {
        var columns = new List<Generated>();

        foreach (var field in snapshot.ArrowSchema.FieldsList)
        {
            if (field.Metadata is null
                || !field.Metadata.TryGetValue("delta.generationExpression", out var sql))
            {
                continue;
            }

            try
            {
                columns.Add(new Generated(field.Name, sql, SparkSqlParser.ParseExpression(sql), field));
            }
            catch (SparkSqlParseException ex)
            {
                throw new DeltaFormatException(
                    DeltaTableErrorCodes.UnevaluableTableExpression,
                    $"Column '{field.Name}' is generated by an expression this writer cannot parse, "
                    + $"so the write was refused rather than committed with a value nobody computed: "
                    + $"{ex.Reason} at position {ex.Position} in: {sql}",
                    ex);
            }
        }

        return columns.Count == 0 ? null : new DeltaGeneratedColumns(columns);
    }

    /// <summary>
    /// Returns <paramref name="batch"/> with every generated column present and correct.
    /// </summary>
    /// <exception cref="DeltaFormatException">
    /// A supplied value disagrees with the expression, or the expression cannot be evaluated.
    /// </exception>
    public RecordBatch Apply(RecordBatch batch)
    {
        var result = batch;

        foreach (var column in _columns)
        {
            // Computed the same way whether it is about to be stored or about to be compared
            // against, which is the point: a caller must be able to supply the value the table
            // would have written.
            var computed = Compute(column, result);

            if (IndexOf(result, column.Name) >= 0)
                ValidateSupplied(column, result, computed);
            else
                result = Append(column, result, computed);
        }

        return result;
    }

    /// <summary>Evaluates the generation expression as the column's declared type.</summary>
    /// <remarks>
    /// Materialised against the declared Arrow type rather than whatever the expression happens
    /// to produce, so <c>CAST(ts AS DATE)</c> lands as the table's DATE column instead of
    /// something merely date-shaped — and so a <c>decimal(10,2)</c> column generated from a
    /// <c>decimal(10,4)</c> expression carries the rescaled value that will actually be written.
    /// </remarks>
    private IArrowArray Compute(Generated column, RecordBatch batch)
    {
        try
        {
            return _evaluator.EvaluateExpression(column.Expression, batch, column.Field.DataType);
        }
        catch (Exception ex) when (ex is not DeltaFormatException)
        {
            throw Unevaluable(column, ex);
        }
    }

    /// <summary>Checks a caller-supplied value against the value that would be stored.</summary>
    /// <remarks>
    /// Compared against <paramref name="computed"/> rather than against the raw expression, and
    /// the difference is reachable: a <c>decimal(10,2)</c> column generated from a
    /// <c>decimal(10,4)</c> expression stores 1.23 where the expression yields 1.2345. Comparing
    /// against the expression would reject a caller supplying 1.23 — the very value the table
    /// writes — leaving the column impossible to supply explicitly at all.
    ///
    /// The comparison itself is the protocol's, <c>(&lt;value&gt; &lt;=&gt; &lt;generated&gt;)
    /// IS TRUE</c>, evaluated through the shared evaluator so its null-safe semantics are the
    /// ones used rather than a second implementation of them.
    /// </remarks>
    private void ValidateSupplied(Generated column, RecordBatch batch, IArrowArray computed)
    {
        const string suppliedName = "__ew_supplied";
        const string computedName = "__ew_generated";

        var schema = new Apache.Arrow.Schema.Builder()
            .Field(new Field(suppliedName, batch.Column(IndexOf(batch, column.Name)).Data.DataType, true))
            .Field(new Field(computedName, computed.Data.DataType, true))
            .Build();

        var pair = new RecordBatch(
            schema,
            [batch.Column(IndexOf(batch, column.Name)), computed],
            batch.Length);

        var agrees = new ComparisonPredicate(
            new UnboundReference(suppliedName),
            ComparisonOperator.NullSafeEqual,
            new UnboundReference(computedName));

        BooleanArray result;
        try
        {
            result = _evaluator.EvaluatePredicate(agrees, pair);
        }
        catch (Exception ex) when (ex is not DeltaFormatException)
        {
            throw Unevaluable(column, ex);
        }

        for (var row = 0; row < batch.Length; row++)
        {
            if (result.GetValue(row) is true)
                continue;

            throw new DeltaFormatException(
                DeltaTableErrorCodes.GeneratedColumnMismatch,
                $"Column '{column.Name}' is GENERATED ALWAYS AS ({column.Sql}), and a row being "
                + "written supplies a value the expression does not produce. Either omit the "
                + "column and let it be computed, or supply the value the expression gives. "
                + "No data was committed.");
        }
    }

    /// <summary>Adds the computed column to the batch.</summary>
    private static RecordBatch Append(Generated column, RecordBatch batch, IArrowArray values)
    {
        var schema = new Apache.Arrow.Schema.Builder();
        var arrays = new List<IArrowArray>(batch.ColumnCount + 1);

        for (var i = 0; i < batch.ColumnCount; i++)
        {
            schema.Field(batch.Schema.FieldsList[i]);
            arrays.Add(batch.Column(i));
        }

        schema.Field(column.Field);
        arrays.Add(values);

        return new RecordBatch(schema.Build(), arrays, batch.Length);
    }

    private static DeltaFormatException Unevaluable(Generated column, Exception cause) =>
        new(
            DeltaTableErrorCodes.UnevaluableTableExpression,
            $"Column '{column.Name}' is generated by ({column.Sql}), which could not be evaluated "
            + $"against the data being written, so the write was refused: {cause.Message}",
            cause);

    private static int IndexOf(RecordBatch batch, string name)
    {
        for (var i = 0; i < batch.ColumnCount; i++)
        {
            if (string.Equals(batch.Schema.FieldsList[i].Name, name, StringComparison.Ordinal))
                return i;
        }

        return -1;
    }
}
